### ISSUE TITLE
How could I post a query to the Solr collection created by Opentapioca?

### ISSUE THREAD

**Issue by heathersherry** [wetneb/opentapioca#15]
Dear authors,

Sorry to have disturbed again! Thanks a lot for the great project and I have really learned a lot from your work.
I have one minor questions about the Solr collection created by TaggerFactory. Is it possible for me to post a query to the collection after the index-dump? 

For example, if I want to search an item, e.g., Q31, in the ordinary Solr cases, I will use `curl "http://localhost:8983/solr/techproducts/select?q=Q31"` or raise a JSON post request. I tried this curl command, and the feedback is as follows:

```
xxx@xxx:/data2/xxx$ curl "http://localhost:8983/solr/cony_collection_8/select"
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr/cony_collection_8/select. Reason:
<pre>    Not Found</pre></p>
</body>
</html>
```
So may I ask how can I post a query to the Solr collection created by Opentapioca after the index-dump step?  Could you please give a simple example?

**Comment by heathersherry** [comment]
<img width="868" alt="Screen Shot 2019-12-17 at 4 50 27 PM" src="https://user-images.githubusercontent.com/1947675/70979957-71fd8700-20ed-11ea-9104-b13296078bfe.png">
Here is the UI interface for the query part.

**Comment by wetneb** [comment]
Hi!

The collection is not designed to provide a classic full-text index on the documents: the only endpoint that is added by the collection configuration is the one to tag some text.

This should be easy to fix if you can run index-dump again. You need to create a new configset where you can turn on indexing for specific indices in the [managed-schema](https://github.com/wetneb/opentapioca/blob/master/configsets/tapioca/conf/managed-schema) (by setting `index="true"` instead of `index="false"`). For instance, the `label` field could be something you could want to index.
You will also need to add a request handler similar to [the one that is already defined for name_tag](https://github.com/wetneb/opentapioca/blob/master/configsets/tapioca/conf/solrconfig.xml#L681), for instance for the `label` field.

There might be ways to do both of these additions on an existing collection but I am not sure how!

**Comment by heathersherry** [comment]
Thanks a lot for your quick feedback! I can conduct the query now. :))))

**Comment by wetneb** [comment]
Awesome! Did you have to reindex or did you find a way to add the endpoint to the existing collection? It'd be curious to know how you did it!

**Comment by heathersherry** [comment]
Haha, I tried several methods to do both additions to the existing collections, but all methods do not work. So finally I redo `bin/solr zk -upconfig -z localhost:9983 -n tapioca -d configsets/tapioca` to upload the new config to Solr, and run index-dump again. I guess this may be the only way that works. :)
Thanks again for your help and suggestion!
